# Generated by Django 5.2.6 on 2025-09-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['posted_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['posted_on']},
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
